package com.trang.TrangWebYTe.model;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.userName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String img;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.id
	 * @return  the value of admin.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.id
	 * @param id  the value for admin.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.fullName
	 * @return  the value of admin.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.fullName
	 * @param fullname  the value for admin.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.userName
	 * @return  the value of admin.userName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.userName
	 * @param username  the value for admin.userName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.email
	 * @return  the value of admin.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.email
	 * @param email  the value for admin.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.phone
	 * @return  the value of admin.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.phone
	 * @param phone  the value for admin.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.img
	 * @return  the value of admin.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.img
	 * @param img  the value for admin.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setImg(String img) {
		this.img = img;
	}
}