package com.trang.TrangWebYTe.model;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.id
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.fullName
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.userName
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.password
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.email
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.phone
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.roleId
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.id
	 * @return  the value of admin.id
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.id
	 * @param id  the value for admin.id
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.fullName
	 * @return  the value of admin.fullName
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.fullName
	 * @param fullname  the value for admin.fullName
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.userName
	 * @return  the value of admin.userName
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.userName
	 * @param username  the value for admin.userName
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.password
	 * @return  the value of admin.password
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.password
	 * @param password  the value for admin.password
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.email
	 * @return  the value of admin.email
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.email
	 * @param email  the value for admin.email
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.phone
	 * @return  the value of admin.phone
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.phone
	 * @param phone  the value for admin.phone
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.roleId
	 * @return  the value of admin.roleId
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.roleId
	 * @param roleid  the value for admin.roleId
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
}