package com.trang.TrangWebYTe.model;

public class BacSi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.makhoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer makhoa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bacsi.username
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.id
	 * @return  the value of bacsi.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.id
	 * @param id  the value for bacsi.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.fullName
	 * @return  the value of bacsi.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.fullName
	 * @param fullname  the value for bacsi.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.email
	 * @return  the value of bacsi.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.email
	 * @param email  the value for bacsi.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.phone
	 * @return  the value of bacsi.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.phone
	 * @param phone  the value for bacsi.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.makhoa
	 * @return  the value of bacsi.makhoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMakhoa() {
		return makhoa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.makhoa
	 * @param makhoa  the value for bacsi.makhoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMakhoa(Integer makhoa) {
		this.makhoa = makhoa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.img
	 * @return  the value of bacsi.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.img
	 * @param img  the value for bacsi.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bacsi.username
	 * @return  the value of bacsi.username
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bacsi.username
	 * @param username  the value for bacsi.username
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}