package com.trang.TrangWebYTe.model;

public class Benh {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column benh.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer ma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column benh.tenbenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String tenbenh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column benh.maloaibenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer maloaibenh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column benh.ma
	 * @return  the value of benh.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMa() {
		return ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column benh.ma
	 * @param ma  the value for benh.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMa(Integer ma) {
		this.ma = ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column benh.tenbenh
	 * @return  the value of benh.tenbenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTenbenh() {
		return tenbenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column benh.tenbenh
	 * @param tenbenh  the value for benh.tenbenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTenbenh(String tenbenh) {
		this.tenbenh = tenbenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column benh.maloaibenh
	 * @return  the value of benh.maloaibenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMaloaibenh() {
		return maloaibenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column benh.maloaibenh
	 * @param maloaibenh  the value for benh.maloaibenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMaloaibenh(Integer maloaibenh) {
		this.maloaibenh = maloaibenh;
	}
}