package com.trang.TrangWebYTe.model;

import java.util.ArrayList;
import java.util.List;

public class BenhExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public BenhExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMaIsNull() {
			addCriterion("ma is null");
			return (Criteria) this;
		}

		public Criteria andMaIsNotNull() {
			addCriterion("ma is not null");
			return (Criteria) this;
		}

		public Criteria andMaEqualTo(Integer value) {
			addCriterion("ma =", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaNotEqualTo(Integer value) {
			addCriterion("ma <>", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaGreaterThan(Integer value) {
			addCriterion("ma >", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ma >=", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaLessThan(Integer value) {
			addCriterion("ma <", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaLessThanOrEqualTo(Integer value) {
			addCriterion("ma <=", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaIn(List<Integer> values) {
			addCriterion("ma in", values, "ma");
			return (Criteria) this;
		}

		public Criteria andMaNotIn(List<Integer> values) {
			addCriterion("ma not in", values, "ma");
			return (Criteria) this;
		}

		public Criteria andMaBetween(Integer value1, Integer value2) {
			addCriterion("ma between", value1, value2, "ma");
			return (Criteria) this;
		}

		public Criteria andMaNotBetween(Integer value1, Integer value2) {
			addCriterion("ma not between", value1, value2, "ma");
			return (Criteria) this;
		}

		public Criteria andTenbenhIsNull() {
			addCriterion("tenbenh is null");
			return (Criteria) this;
		}

		public Criteria andTenbenhIsNotNull() {
			addCriterion("tenbenh is not null");
			return (Criteria) this;
		}

		public Criteria andTenbenhEqualTo(String value) {
			addCriterion("tenbenh =", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhNotEqualTo(String value) {
			addCriterion("tenbenh <>", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhGreaterThan(String value) {
			addCriterion("tenbenh >", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhGreaterThanOrEqualTo(String value) {
			addCriterion("tenbenh >=", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhLessThan(String value) {
			addCriterion("tenbenh <", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhLessThanOrEqualTo(String value) {
			addCriterion("tenbenh <=", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhLike(String value) {
			addCriterion("tenbenh like", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhNotLike(String value) {
			addCriterion("tenbenh not like", value, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhIn(List<String> values) {
			addCriterion("tenbenh in", values, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhNotIn(List<String> values) {
			addCriterion("tenbenh not in", values, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhBetween(String value1, String value2) {
			addCriterion("tenbenh between", value1, value2, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andTenbenhNotBetween(String value1, String value2) {
			addCriterion("tenbenh not between", value1, value2, "tenbenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhIsNull() {
			addCriterion("maloaibenh is null");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhIsNotNull() {
			addCriterion("maloaibenh is not null");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhEqualTo(Integer value) {
			addCriterion("maloaibenh =", value, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhNotEqualTo(Integer value) {
			addCriterion("maloaibenh <>", value, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhGreaterThan(Integer value) {
			addCriterion("maloaibenh >", value, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhGreaterThanOrEqualTo(Integer value) {
			addCriterion("maloaibenh >=", value, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhLessThan(Integer value) {
			addCriterion("maloaibenh <", value, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhLessThanOrEqualTo(Integer value) {
			addCriterion("maloaibenh <=", value, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhIn(List<Integer> values) {
			addCriterion("maloaibenh in", values, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhNotIn(List<Integer> values) {
			addCriterion("maloaibenh not in", values, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhBetween(Integer value1, Integer value2) {
			addCriterion("maloaibenh between", value1, value2, "maloaibenh");
			return (Criteria) this;
		}

		public Criteria andMaloaibenhNotBetween(Integer value1, Integer value2) {
			addCriterion("maloaibenh not between", value1, value2, "maloaibenh");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table benh
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 02 22:32:48 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}