package com.trang.TrangWebYTe.model;

public class ChiTietToaThuocKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitiettoathuoc.matoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer matoathuoc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitiettoathuoc.mathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer mathuoc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitiettoathuoc.matoathuoc
	 * @return  the value of chitiettoathuoc.matoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMatoathuoc() {
		return matoathuoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitiettoathuoc.matoathuoc
	 * @param matoathuoc  the value for chitiettoathuoc.matoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMatoathuoc(Integer matoathuoc) {
		this.matoathuoc = matoathuoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitiettoathuoc.mathuoc
	 * @return  the value of chitiettoathuoc.mathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMathuoc() {
		return mathuoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitiettoathuoc.mathuoc
	 * @param mathuoc  the value for chitiettoathuoc.mathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMathuoc(Integer mathuoc) {
		this.mathuoc = mathuoc;
	}
}