package com.trang.TrangWebYTe.model;

public class ChiTietToaThuoc extends ChiTietToaThuocKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitiettoathuoc.soluongdung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer soluongdung;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitiettoathuoc.cachdung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String cachdung;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitiettoathuoc.soluongdung
	 * @return  the value of chitiettoathuoc.soluongdung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getSoluongdung() {
		return soluongdung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitiettoathuoc.soluongdung
	 * @param soluongdung  the value for chitiettoathuoc.soluongdung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setSoluongdung(Integer soluongdung) {
		this.soluongdung = soluongdung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitiettoathuoc.cachdung
	 * @return  the value of chitiettoathuoc.cachdung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getCachdung() {
		return cachdung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitiettoathuoc.cachdung
	 * @param cachdung  the value for chitiettoathuoc.cachdung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setCachdung(String cachdung) {
		this.cachdung = cachdung;
	}
}