package com.trang.TrangWebYTe.model;

import java.util.ArrayList;
import java.util.List;

public class ChiTietToaThuocExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public ChiTietToaThuocExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMatoathuocIsNull() {
			addCriterion("matoathuoc is null");
			return (Criteria) this;
		}

		public Criteria andMatoathuocIsNotNull() {
			addCriterion("matoathuoc is not null");
			return (Criteria) this;
		}

		public Criteria andMatoathuocEqualTo(Integer value) {
			addCriterion("matoathuoc =", value, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocNotEqualTo(Integer value) {
			addCriterion("matoathuoc <>", value, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocGreaterThan(Integer value) {
			addCriterion("matoathuoc >", value, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocGreaterThanOrEqualTo(Integer value) {
			addCriterion("matoathuoc >=", value, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocLessThan(Integer value) {
			addCriterion("matoathuoc <", value, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocLessThanOrEqualTo(Integer value) {
			addCriterion("matoathuoc <=", value, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocIn(List<Integer> values) {
			addCriterion("matoathuoc in", values, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocNotIn(List<Integer> values) {
			addCriterion("matoathuoc not in", values, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocBetween(Integer value1, Integer value2) {
			addCriterion("matoathuoc between", value1, value2, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMatoathuocNotBetween(Integer value1, Integer value2) {
			addCriterion("matoathuoc not between", value1, value2, "matoathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocIsNull() {
			addCriterion("mathuoc is null");
			return (Criteria) this;
		}

		public Criteria andMathuocIsNotNull() {
			addCriterion("mathuoc is not null");
			return (Criteria) this;
		}

		public Criteria andMathuocEqualTo(Integer value) {
			addCriterion("mathuoc =", value, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocNotEqualTo(Integer value) {
			addCriterion("mathuoc <>", value, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocGreaterThan(Integer value) {
			addCriterion("mathuoc >", value, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocGreaterThanOrEqualTo(Integer value) {
			addCriterion("mathuoc >=", value, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocLessThan(Integer value) {
			addCriterion("mathuoc <", value, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocLessThanOrEqualTo(Integer value) {
			addCriterion("mathuoc <=", value, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocIn(List<Integer> values) {
			addCriterion("mathuoc in", values, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocNotIn(List<Integer> values) {
			addCriterion("mathuoc not in", values, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocBetween(Integer value1, Integer value2) {
			addCriterion("mathuoc between", value1, value2, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andMathuocNotBetween(Integer value1, Integer value2) {
			addCriterion("mathuoc not between", value1, value2, "mathuoc");
			return (Criteria) this;
		}

		public Criteria andSoluongdungIsNull() {
			addCriterion("soluongdung is null");
			return (Criteria) this;
		}

		public Criteria andSoluongdungIsNotNull() {
			addCriterion("soluongdung is not null");
			return (Criteria) this;
		}

		public Criteria andSoluongdungEqualTo(Integer value) {
			addCriterion("soluongdung =", value, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungNotEqualTo(Integer value) {
			addCriterion("soluongdung <>", value, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungGreaterThan(Integer value) {
			addCriterion("soluongdung >", value, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungGreaterThanOrEqualTo(Integer value) {
			addCriterion("soluongdung >=", value, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungLessThan(Integer value) {
			addCriterion("soluongdung <", value, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungLessThanOrEqualTo(Integer value) {
			addCriterion("soluongdung <=", value, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungIn(List<Integer> values) {
			addCriterion("soluongdung in", values, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungNotIn(List<Integer> values) {
			addCriterion("soluongdung not in", values, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungBetween(Integer value1, Integer value2) {
			addCriterion("soluongdung between", value1, value2, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andSoluongdungNotBetween(Integer value1, Integer value2) {
			addCriterion("soluongdung not between", value1, value2, "soluongdung");
			return (Criteria) this;
		}

		public Criteria andCachdungIsNull() {
			addCriterion("cachdung is null");
			return (Criteria) this;
		}

		public Criteria andCachdungIsNotNull() {
			addCriterion("cachdung is not null");
			return (Criteria) this;
		}

		public Criteria andCachdungEqualTo(String value) {
			addCriterion("cachdung =", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungNotEqualTo(String value) {
			addCriterion("cachdung <>", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungGreaterThan(String value) {
			addCriterion("cachdung >", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungGreaterThanOrEqualTo(String value) {
			addCriterion("cachdung >=", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungLessThan(String value) {
			addCriterion("cachdung <", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungLessThanOrEqualTo(String value) {
			addCriterion("cachdung <=", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungLike(String value) {
			addCriterion("cachdung like", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungNotLike(String value) {
			addCriterion("cachdung not like", value, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungIn(List<String> values) {
			addCriterion("cachdung in", values, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungNotIn(List<String> values) {
			addCriterion("cachdung not in", values, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungBetween(String value1, String value2) {
			addCriterion("cachdung between", value1, value2, "cachdung");
			return (Criteria) this;
		}

		public Criteria andCachdungNotBetween(String value1, String value2) {
			addCriterion("cachdung not between", value1, value2, "cachdung");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chitiettoathuoc
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 27 16:00:09 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}