package com.trang.TrangWebYTe.model;

public class ChiTietSoTiemChungKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsotiemchung.masotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer masotiemchung;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsotiemchung.mavaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer mavaccine;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsotiemchung.masotiemchung
	 * @return  the value of chitietsotiemchung.masotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMasotiemchung() {
		return masotiemchung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsotiemchung.masotiemchung
	 * @param masotiemchung  the value for chitietsotiemchung.masotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMasotiemchung(Integer masotiemchung) {
		this.masotiemchung = masotiemchung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsotiemchung.mavaccine
	 * @return  the value of chitietsotiemchung.mavaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMavaccine() {
		return mavaccine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsotiemchung.mavaccine
	 * @param mavaccine  the value for chitietsotiemchung.mavaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMavaccine(Integer mavaccine) {
		this.mavaccine = mavaccine;
	}
}