package com.trang.TrangWebYTe.model;

public class chitietSoKhamBenhKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsokhambenh.masokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer masokhambenh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsokhambenh.mabenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer mabenh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsokhambenh.masokhambenh
	 * @return  the value of chitietsokhambenh.masokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMasokhambenh() {
		return masokhambenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsokhambenh.masokhambenh
	 * @param masokhambenh  the value for chitietsokhambenh.masokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMasokhambenh(Integer masokhambenh) {
		this.masokhambenh = masokhambenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsokhambenh.mabenh
	 * @return  the value of chitietsokhambenh.mabenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMabenh() {
		return mabenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsokhambenh.mabenh
	 * @param mabenh  the value for chitietsokhambenh.mabenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMabenh(Integer mabenh) {
		this.mabenh = mabenh;
	}
}