package com.trang.TrangWebYTe.model;

public class ChiTietSoTiemChung extends ChiTietSoTiemChungKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsotiemchung.solieu
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer solieu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsotiemchung.trieuchungsautiem
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String trieuchungsautiem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chitietsotiemchung.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String trangthai;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsotiemchung.solieu
	 * @return  the value of chitietsotiemchung.solieu
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getSolieu() {
		return solieu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsotiemchung.solieu
	 * @param solieu  the value for chitietsotiemchung.solieu
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setSolieu(Integer solieu) {
		this.solieu = solieu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsotiemchung.trieuchungsautiem
	 * @return  the value of chitietsotiemchung.trieuchungsautiem
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTrieuchungsautiem() {
		return trieuchungsautiem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsotiemchung.trieuchungsautiem
	 * @param trieuchungsautiem  the value for chitietsotiemchung.trieuchungsautiem
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTrieuchungsautiem(String trieuchungsautiem) {
		this.trieuchungsautiem = trieuchungsautiem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chitietsotiemchung.trangthai
	 * @return  the value of chitietsotiemchung.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTrangthai() {
		return trangthai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chitietsotiemchung.trangthai
	 * @param trangthai  the value for chitietsotiemchung.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}
}