package com.trang.TrangWebYTe.model;

public class Khoa {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column khoa.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer ma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column khoa.tenkhoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String tenkhoa;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column khoa.ma
	 * @return  the value of khoa.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMa() {
		return ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column khoa.ma
	 * @param ma  the value for khoa.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMa(Integer ma) {
		this.ma = ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column khoa.tenkhoa
	 * @return  the value of khoa.tenkhoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTenkhoa() {
		return tenkhoa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column khoa.tenkhoa
	 * @param tenkhoa  the value for khoa.tenkhoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTenkhoa(String tenkhoa) {
		this.tenkhoa = tenkhoa;
	}
}