package com.trang.TrangWebYTe.model;

import java.util.Date;

public class LichTruc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichtruc.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer ma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichtruc.mabacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer mabacsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichtruc.ngaytruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date ngaytruc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichtruc.Tuan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String tuan;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichtruc.ma
	 * @return  the value of lichtruc.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMa() {
		return ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichtruc.ma
	 * @param ma  the value for lichtruc.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMa(Integer ma) {
		this.ma = ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichtruc.mabacsi
	 * @return  the value of lichtruc.mabacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMabacsi() {
		return mabacsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichtruc.mabacsi
	 * @param mabacsi  the value for lichtruc.mabacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMabacsi(Integer mabacsi) {
		this.mabacsi = mabacsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichtruc.ngaytruc
	 * @return  the value of lichtruc.ngaytruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getNgaytruc() {
		return ngaytruc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichtruc.ngaytruc
	 * @param ngaytruc  the value for lichtruc.ngaytruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNgaytruc(Date ngaytruc) {
		this.ngaytruc = ngaytruc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichtruc.Tuan
	 * @return  the value of lichtruc.Tuan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTuan() {
		return tuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichtruc.Tuan
	 * @param tuan  the value for lichtruc.Tuan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTuan(String tuan) {
		this.tuan = tuan;
	}
}