package com.trang.TrangWebYTe.model;

import java.util.Date;

public class LichKham {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichkham.idlichkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer idlichkham;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichkham.mabacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer mabacsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichkham.userId
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichkham.ngayhenkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date ngayhenkham;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lichkham.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String trangthai;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichkham.idlichkham
	 * @return  the value of lichkham.idlichkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getIdlichkham() {
		return idlichkham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichkham.idlichkham
	 * @param idlichkham  the value for lichkham.idlichkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setIdlichkham(Integer idlichkham) {
		this.idlichkham = idlichkham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichkham.mabacsi
	 * @return  the value of lichkham.mabacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMabacsi() {
		return mabacsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichkham.mabacsi
	 * @param mabacsi  the value for lichkham.mabacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMabacsi(Integer mabacsi) {
		this.mabacsi = mabacsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichkham.userId
	 * @return  the value of lichkham.userId
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichkham.userId
	 * @param userid  the value for lichkham.userId
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichkham.ngayhenkham
	 * @return  the value of lichkham.ngayhenkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getNgayhenkham() {
		return ngayhenkham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichkham.ngayhenkham
	 * @param ngayhenkham  the value for lichkham.ngayhenkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNgayhenkham(Date ngayhenkham) {
		this.ngayhenkham = ngayhenkham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lichkham.trangthai
	 * @return  the value of lichkham.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTrangthai() {
		return trangthai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lichkham.trangthai
	 * @param trangthai  the value for lichkham.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}
}