package com.trang.TrangWebYTe.model;

import java.util.Date;

public class News {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.idNews
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer idnews;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.tieude
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String tieude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.noidung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String noidung;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.noidungthugon
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String noidungthugon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.ngaytao
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date ngaytao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.idadmin
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer idadmin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.idNews
	 * @return  the value of news.idNews
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getIdnews() {
		return idnews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.idNews
	 * @param idnews  the value for news.idNews
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setIdnews(Integer idnews) {
		this.idnews = idnews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.tieude
	 * @return  the value of news.tieude
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTieude() {
		return tieude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.tieude
	 * @param tieude  the value for news.tieude
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTieude(String tieude) {
		this.tieude = tieude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.noidung
	 * @return  the value of news.noidung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getNoidung() {
		return noidung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.noidung
	 * @param noidung  the value for news.noidung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.noidungthugon
	 * @return  the value of news.noidungthugon
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getNoidungthugon() {
		return noidungthugon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.noidungthugon
	 * @param noidungthugon  the value for news.noidungthugon
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNoidungthugon(String noidungthugon) {
		this.noidungthugon = noidungthugon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.img
	 * @return  the value of news.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.img
	 * @param img  the value for news.img
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.ngaytao
	 * @return  the value of news.ngaytao
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getNgaytao() {
		return ngaytao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.ngaytao
	 * @param ngaytao  the value for news.ngaytao
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.idadmin
	 * @return  the value of news.idadmin
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getIdadmin() {
		return idadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.idadmin
	 * @param idadmin  the value for news.idadmin
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setIdadmin(Integer idadmin) {
		this.idadmin = idadmin;
	}
}