package com.trang.TrangWebYTe.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class NewsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public NewsExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdnewsIsNull() {
			addCriterion("idNews is null");
			return (Criteria) this;
		}

		public Criteria andIdnewsIsNotNull() {
			addCriterion("idNews is not null");
			return (Criteria) this;
		}

		public Criteria andIdnewsEqualTo(Integer value) {
			addCriterion("idNews =", value, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsNotEqualTo(Integer value) {
			addCriterion("idNews <>", value, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsGreaterThan(Integer value) {
			addCriterion("idNews >", value, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsGreaterThanOrEqualTo(Integer value) {
			addCriterion("idNews >=", value, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsLessThan(Integer value) {
			addCriterion("idNews <", value, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsLessThanOrEqualTo(Integer value) {
			addCriterion("idNews <=", value, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsIn(List<Integer> values) {
			addCriterion("idNews in", values, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsNotIn(List<Integer> values) {
			addCriterion("idNews not in", values, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsBetween(Integer value1, Integer value2) {
			addCriterion("idNews between", value1, value2, "idnews");
			return (Criteria) this;
		}

		public Criteria andIdnewsNotBetween(Integer value1, Integer value2) {
			addCriterion("idNews not between", value1, value2, "idnews");
			return (Criteria) this;
		}

		public Criteria andTieudeIsNull() {
			addCriterion("tieude is null");
			return (Criteria) this;
		}

		public Criteria andTieudeIsNotNull() {
			addCriterion("tieude is not null");
			return (Criteria) this;
		}

		public Criteria andTieudeEqualTo(String value) {
			addCriterion("tieude =", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeNotEqualTo(String value) {
			addCriterion("tieude <>", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeGreaterThan(String value) {
			addCriterion("tieude >", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeGreaterThanOrEqualTo(String value) {
			addCriterion("tieude >=", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeLessThan(String value) {
			addCriterion("tieude <", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeLessThanOrEqualTo(String value) {
			addCriterion("tieude <=", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeLike(String value) {
			addCriterion("tieude like", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeNotLike(String value) {
			addCriterion("tieude not like", value, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeIn(List<String> values) {
			addCriterion("tieude in", values, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeNotIn(List<String> values) {
			addCriterion("tieude not in", values, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeBetween(String value1, String value2) {
			addCriterion("tieude between", value1, value2, "tieude");
			return (Criteria) this;
		}

		public Criteria andTieudeNotBetween(String value1, String value2) {
			addCriterion("tieude not between", value1, value2, "tieude");
			return (Criteria) this;
		}

		public Criteria andNoidungIsNull() {
			addCriterion("noidung is null");
			return (Criteria) this;
		}

		public Criteria andNoidungIsNotNull() {
			addCriterion("noidung is not null");
			return (Criteria) this;
		}

		public Criteria andNoidungEqualTo(String value) {
			addCriterion("noidung =", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungNotEqualTo(String value) {
			addCriterion("noidung <>", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungGreaterThan(String value) {
			addCriterion("noidung >", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungGreaterThanOrEqualTo(String value) {
			addCriterion("noidung >=", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungLessThan(String value) {
			addCriterion("noidung <", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungLessThanOrEqualTo(String value) {
			addCriterion("noidung <=", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungLike(String value) {
			addCriterion("noidung like", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungNotLike(String value) {
			addCriterion("noidung not like", value, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungIn(List<String> values) {
			addCriterion("noidung in", values, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungNotIn(List<String> values) {
			addCriterion("noidung not in", values, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungBetween(String value1, String value2) {
			addCriterion("noidung between", value1, value2, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungNotBetween(String value1, String value2) {
			addCriterion("noidung not between", value1, value2, "noidung");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonIsNull() {
			addCriterion("noidungthugon is null");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonIsNotNull() {
			addCriterion("noidungthugon is not null");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonEqualTo(String value) {
			addCriterion("noidungthugon =", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonNotEqualTo(String value) {
			addCriterion("noidungthugon <>", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonGreaterThan(String value) {
			addCriterion("noidungthugon >", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonGreaterThanOrEqualTo(String value) {
			addCriterion("noidungthugon >=", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonLessThan(String value) {
			addCriterion("noidungthugon <", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonLessThanOrEqualTo(String value) {
			addCriterion("noidungthugon <=", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonLike(String value) {
			addCriterion("noidungthugon like", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonNotLike(String value) {
			addCriterion("noidungthugon not like", value, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonIn(List<String> values) {
			addCriterion("noidungthugon in", values, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonNotIn(List<String> values) {
			addCriterion("noidungthugon not in", values, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonBetween(String value1, String value2) {
			addCriterion("noidungthugon between", value1, value2, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andNoidungthugonNotBetween(String value1, String value2) {
			addCriterion("noidungthugon not between", value1, value2, "noidungthugon");
			return (Criteria) this;
		}

		public Criteria andImgIsNull() {
			addCriterion("img is null");
			return (Criteria) this;
		}

		public Criteria andImgIsNotNull() {
			addCriterion("img is not null");
			return (Criteria) this;
		}

		public Criteria andImgEqualTo(String value) {
			addCriterion("img =", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotEqualTo(String value) {
			addCriterion("img <>", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgGreaterThan(String value) {
			addCriterion("img >", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgGreaterThanOrEqualTo(String value) {
			addCriterion("img >=", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLessThan(String value) {
			addCriterion("img <", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLessThanOrEqualTo(String value) {
			addCriterion("img <=", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLike(String value) {
			addCriterion("img like", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotLike(String value) {
			addCriterion("img not like", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgIn(List<String> values) {
			addCriterion("img in", values, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotIn(List<String> values) {
			addCriterion("img not in", values, "img");
			return (Criteria) this;
		}

		public Criteria andImgBetween(String value1, String value2) {
			addCriterion("img between", value1, value2, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotBetween(String value1, String value2) {
			addCriterion("img not between", value1, value2, "img");
			return (Criteria) this;
		}

		public Criteria andNgaytaoIsNull() {
			addCriterion("ngaytao is null");
			return (Criteria) this;
		}

		public Criteria andNgaytaoIsNotNull() {
			addCriterion("ngaytao is not null");
			return (Criteria) this;
		}

		public Criteria andNgaytaoEqualTo(Date value) {
			addCriterionForJDBCDate("ngaytao =", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoNotEqualTo(Date value) {
			addCriterionForJDBCDate("ngaytao <>", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoGreaterThan(Date value) {
			addCriterionForJDBCDate("ngaytao >", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ngaytao >=", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoLessThan(Date value) {
			addCriterionForJDBCDate("ngaytao <", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ngaytao <=", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoIn(List<Date> values) {
			addCriterionForJDBCDate("ngaytao in", values, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoNotIn(List<Date> values) {
			addCriterionForJDBCDate("ngaytao not in", values, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ngaytao between", value1, value2, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ngaytao not between", value1, value2, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andIdadminIsNull() {
			addCriterion("idadmin is null");
			return (Criteria) this;
		}

		public Criteria andIdadminIsNotNull() {
			addCriterion("idadmin is not null");
			return (Criteria) this;
		}

		public Criteria andIdadminEqualTo(Integer value) {
			addCriterion("idadmin =", value, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminNotEqualTo(Integer value) {
			addCriterion("idadmin <>", value, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminGreaterThan(Integer value) {
			addCriterion("idadmin >", value, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminGreaterThanOrEqualTo(Integer value) {
			addCriterion("idadmin >=", value, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminLessThan(Integer value) {
			addCriterion("idadmin <", value, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminLessThanOrEqualTo(Integer value) {
			addCriterion("idadmin <=", value, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminIn(List<Integer> values) {
			addCriterion("idadmin in", values, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminNotIn(List<Integer> values) {
			addCriterion("idadmin not in", values, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminBetween(Integer value1, Integer value2) {
			addCriterion("idadmin between", value1, value2, "idadmin");
			return (Criteria) this;
		}

		public Criteria andIdadminNotBetween(Integer value1, Integer value2) {
			addCriterion("idadmin not between", value1, value2, "idadmin");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table news
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 16 17:51:33 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}