package com.trang.TrangWebYTe.model;

import java.util.Date;

public class SoKhamBenh {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sokhambenh.masokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer masokhambenh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sokhambenh.ngaykham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date ngaykham;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sokhambenh.malichkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer malichkham;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sokhambenh.matoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer matoathuoc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sokhambenh.masokhambenh
	 * @return  the value of sokhambenh.masokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMasokhambenh() {
		return masokhambenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sokhambenh.masokhambenh
	 * @param masokhambenh  the value for sokhambenh.masokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMasokhambenh(Integer masokhambenh) {
		this.masokhambenh = masokhambenh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sokhambenh.ngaykham
	 * @return  the value of sokhambenh.ngaykham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getNgaykham() {
		return ngaykham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sokhambenh.ngaykham
	 * @param ngaykham  the value for sokhambenh.ngaykham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNgaykham(Date ngaykham) {
		this.ngaykham = ngaykham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sokhambenh.malichkham
	 * @return  the value of sokhambenh.malichkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMalichkham() {
		return malichkham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sokhambenh.malichkham
	 * @param malichkham  the value for sokhambenh.malichkham
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMalichkham(Integer malichkham) {
		this.malichkham = malichkham;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sokhambenh.matoathuoc
	 * @return  the value of sokhambenh.matoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMatoathuoc() {
		return matoathuoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sokhambenh.matoathuoc
	 * @param matoathuoc  the value for sokhambenh.matoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMatoathuoc(Integer matoathuoc) {
		this.matoathuoc = matoathuoc;
	}
}