package com.trang.TrangWebYTe.model;

public class TaiKhoan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taikhoan.username
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taikhoan.password
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taikhoan.idrole
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer idrole;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taikhoan.username
	 * @return  the value of taikhoan.username
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taikhoan.username
	 * @param username  the value for taikhoan.username
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taikhoan.password
	 * @return  the value of taikhoan.password
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taikhoan.password
	 * @param password  the value for taikhoan.password
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taikhoan.idrole
	 * @return  the value of taikhoan.idrole
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getIdrole() {
		return idrole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taikhoan.idrole
	 * @param idrole  the value for taikhoan.idrole
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setIdrole(Integer idrole) {
		this.idrole = idrole;
	}
}