package com.trang.TrangWebYTe.model;

import java.util.Date;

public class Thuoc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer ma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.tenthuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String tenthuoc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.soluong
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer soluong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.ngaynhap
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date ngaynhap;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.hansudung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date hansudung;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String trangthai;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thuoc.donggoi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String donggoi;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.ma
	 * @return  the value of thuoc.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMa() {
		return ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.ma
	 * @param ma  the value for thuoc.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMa(Integer ma) {
		this.ma = ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.tenthuoc
	 * @return  the value of thuoc.tenthuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTenthuoc() {
		return tenthuoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.tenthuoc
	 * @param tenthuoc  the value for thuoc.tenthuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTenthuoc(String tenthuoc) {
		this.tenthuoc = tenthuoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.soluong
	 * @return  the value of thuoc.soluong
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getSoluong() {
		return soluong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.soluong
	 * @param soluong  the value for thuoc.soluong
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.ngaynhap
	 * @return  the value of thuoc.ngaynhap
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getNgaynhap() {
		return ngaynhap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.ngaynhap
	 * @param ngaynhap  the value for thuoc.ngaynhap
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.hansudung
	 * @return  the value of thuoc.hansudung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getHansudung() {
		return hansudung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.hansudung
	 * @param hansudung  the value for thuoc.hansudung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setHansudung(Date hansudung) {
		this.hansudung = hansudung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.trangthai
	 * @return  the value of thuoc.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTrangthai() {
		return trangthai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.trangthai
	 * @param trangthai  the value for thuoc.trangthai
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thuoc.donggoi
	 * @return  the value of thuoc.donggoi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getDonggoi() {
		return donggoi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thuoc.donggoi
	 * @param donggoi  the value for thuoc.donggoi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setDonggoi(String donggoi) {
		this.donggoi = donggoi;
	}
}