package com.trang.TrangWebYTe.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String phone;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.fullName
	 * @return  the value of user.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.fullName
	 * @param fullname  the value for user.fullName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userName
	 * @return  the value of user.userName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getUsername() {
		return username;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userName
	 * @param username  the value for user.userName
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	
	public String getEmail() {
		return email;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getPhone() {
		return phone;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}
	private Integer roleid;
	public Integer getRoleid() {
		return roleid;
	}
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
	private String img;
	public String getImg() {
		return img;
	}

}