package com.trang.TrangWebYTe.model;

import java.util.Date;

public class Vaccine {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vaccine.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer ma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vaccine.tenvaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String tenvaccine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vaccine.trangthaivaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private String trangthaivaccine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vaccine.ngaynhap
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date ngaynhap;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vaccine.hansudung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Date hansudung;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vaccine.soluong
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	private Integer soluong;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vaccine.ma
	 * @return  the value of vaccine.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getMa() {
		return ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vaccine.ma
	 * @param ma  the value for vaccine.ma
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setMa(Integer ma) {
		this.ma = ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vaccine.tenvaccine
	 * @return  the value of vaccine.tenvaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTenvaccine() {
		return tenvaccine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vaccine.tenvaccine
	 * @param tenvaccine  the value for vaccine.tenvaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTenvaccine(String tenvaccine) {
		this.tenvaccine = tenvaccine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vaccine.trangthaivaccine
	 * @return  the value of vaccine.trangthaivaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public String getTrangthaivaccine() {
		return trangthaivaccine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vaccine.trangthaivaccine
	 * @param trangthaivaccine  the value for vaccine.trangthaivaccine
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setTrangthaivaccine(String trangthaivaccine) {
		this.trangthaivaccine = trangthaivaccine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vaccine.ngaynhap
	 * @return  the value of vaccine.ngaynhap
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getNgaynhap() {
		return ngaynhap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vaccine.ngaynhap
	 * @param ngaynhap  the value for vaccine.ngaynhap
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vaccine.hansudung
	 * @return  the value of vaccine.hansudung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Date getHansudung() {
		return hansudung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vaccine.hansudung
	 * @param hansudung  the value for vaccine.hansudung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setHansudung(Date hansudung) {
		this.hansudung = hansudung;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vaccine.soluong
	 * @return  the value of vaccine.soluong
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public Integer getSoluong() {
		return soluong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vaccine.soluong
	 * @param soluong  the value for vaccine.soluong
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}
}