package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.Admin;
import com.trang.TrangWebYTe.model.AdminExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	long countByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int deleteByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int insertSelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	List<Admin> selectByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByPrimaryKeySelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByPrimaryKey(Admin record);
}