package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.BacSi;
import com.trang.TrangWebYTe.model.BacSiExample;
import com.trang.TrangWebYTe.model.User;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BacSiMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(BacSiExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(BacSiExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(BacSi record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(BacSi record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<BacSi> selectByExample(BacSiExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	BacSi selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") BacSi record, @Param("example") BacSiExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") BacSi record, @Param("example") BacSiExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(BacSi record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bacsi
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(BacSi record);
	List<Map<String, Object>> getAllBacSiTenKhoa();
    List<Map<String, Object>> getAllBacSiTenKhoaTheoten(Map<String, Object> fullname);

    List<Map<String, Object>> getAllBacSiTenKhoaTheoId(Map<String, Object> ma);
   
    BacSi  getAllBacSiTheoTen(Map<String, Object> name);
    int updateByPrimaryKeyBacSi(BacSi record);
}