package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.Benh;
import com.trang.TrangWebYTe.model.BenhExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BenhMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(BenhExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(BenhExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(Benh record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(Benh record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<Benh> selectByExample(BenhExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	Benh selectByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") Benh record, @Param("example") BenhExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") Benh record, @Param("example") BenhExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(Benh record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table benh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(Benh record);
}