package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.ChiTietToaThuoc;
import com.trang.TrangWebYTe.model.ChiTietToaThuocExample;
import com.trang.TrangWebYTe.model.ChiTietToaThuocKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChiTietToaThuocMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(ChiTietToaThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(ChiTietToaThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(ChiTietToaThuocKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(ChiTietToaThuoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(ChiTietToaThuoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<ChiTietToaThuoc> selectByExample(ChiTietToaThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	ChiTietToaThuoc selectByPrimaryKey(ChiTietToaThuocKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") ChiTietToaThuoc record,
			@Param("example") ChiTietToaThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") ChiTietToaThuoc record, @Param("example") ChiTietToaThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(ChiTietToaThuoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitiettoathuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(ChiTietToaThuoc record);
}