package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.chitietSoKhamBenhExample;
import com.trang.TrangWebYTe.model.chitietSoKhamBenhKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface chitietSoKhamBenhMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(chitietSoKhamBenhExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(chitietSoKhamBenhExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(chitietSoKhamBenhKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(chitietSoKhamBenhKey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(chitietSoKhamBenhKey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<chitietSoKhamBenhKey> selectByExample(chitietSoKhamBenhExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") chitietSoKhamBenhKey record,
			@Param("example") chitietSoKhamBenhExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chitietsokhambenh
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") chitietSoKhamBenhKey record,
			@Param("example") chitietSoKhamBenhExample example);
	List<Map<String, Object>> getAllBenh(int ma);
	List<Map<String, Object>> getToaThuoc(int ma);
}