package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.Khoa;
import com.trang.TrangWebYTe.model.KhoaExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface KhoaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(KhoaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(KhoaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(Khoa record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(Khoa record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<Khoa> selectByExample(KhoaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	Khoa selectByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") Khoa record, @Param("example") KhoaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") Khoa record, @Param("example") KhoaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(Khoa record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khoa
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(Khoa record);
}