package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.LichKham;
import com.trang.TrangWebYTe.model.LichKhamExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LichKhamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	long countByExample(LichKhamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int deleteByExample(LichKhamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int deleteByPrimaryKey(Integer idlichkham);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int insert(LichKham record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int insertSelective(LichKham record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	List<LichKham> selectByExample(LichKhamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	LichKham selectByPrimaryKey(Integer idlichkham);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") LichKham record, @Param("example") LichKhamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByExample(@Param("record") LichKham record, @Param("example") LichKhamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByPrimaryKeySelective(LichKham record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichkham
	 * @mbg.generated  Thu Nov 18 23:25:06 ICT 2021
	 */
	int updateByPrimaryKey(LichKham record);
}