package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.LichTruc;
import com.trang.TrangWebYTe.model.LichTrucExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LichTrucMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(LichTrucExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(LichTrucExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(LichTruc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(LichTruc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<LichTruc> selectByExample(LichTrucExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	LichTruc selectByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") LichTruc record, @Param("example") LichTrucExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") LichTruc record, @Param("example") LichTrucExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(LichTruc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lichtruc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(LichTruc record);
}