package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.SoTiemChung;
import com.trang.TrangWebYTe.model.SoTiemChungExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoTiemChungMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(SoTiemChungExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(SoTiemChungExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(SoTiemChung record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(SoTiemChung record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<SoTiemChung> selectByExample(SoTiemChungExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	SoTiemChung selectByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") SoTiemChung record, @Param("example") SoTiemChungExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") SoTiemChung record, @Param("example") SoTiemChungExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(SoTiemChung record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sotiemchung
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(SoTiemChung record);
}