package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.TaiKhoan;
import com.trang.TrangWebYTe.model.TaiKhoanExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaiKhoanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(TaiKhoanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(TaiKhoanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(TaiKhoan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(TaiKhoan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<TaiKhoan> selectByExample(TaiKhoanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	TaiKhoan selectByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") TaiKhoan record, @Param("example") TaiKhoanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") TaiKhoan record, @Param("example") TaiKhoanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(TaiKhoan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table taikhoan
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(TaiKhoan record);

	int updateTaiKhoan( @Param("record") TaiKhoan record, @Param("example") TaiKhoanExample example);
}