package com.trang.TrangWebYTe.mapper;

import com.trang.TrangWebYTe.model.Thuoc;
import com.trang.TrangWebYTe.model.ThuocExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ThuocMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	long countByExample(ThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByExample(ThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int deleteByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insert(Thuoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int insertSelective(Thuoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	List<Thuoc> selectByExample(ThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	Thuoc selectByPrimaryKey(Integer ma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") Thuoc record, @Param("example") ThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByExample(@Param("record") Thuoc record, @Param("example") ThuocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKeySelective(Thuoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thuoc
	 * @mbg.generated  Sun Dec 19 00:24:21 ICT 2021
	 */
	int updateByPrimaryKey(Thuoc record);
}